export const galleryImages = [
  {
    id: 1,
    src: "/boda/6.webp",
    alt: "Compromiso",
    size: "tall",
  },
  {
    id: 2,
    src: "/boda/7.webp",
    alt: "Sesión",
    size: "tall",
  },
  {
    id: 3,
    src: "/boda/1.webp",
    alt: "Momentos",
    size: "wide",
  },
  {
    id: 4,
    src: "/boda/23.webp",
    alt: "Sesión",
    size: "tall",
  },
  {
    id: 5,
    src: "/boda/37.webp",
    alt: "Momentos",
    size: "small",
  },
  {
    id: 6,
    src: "/boda/47.webp",
    alt: "Viaje",
    size: "tall",
  },
  {
    id: 7,
    src: "/boda/50.webp",
    alt: "Sesión",
    size: "small",
  },
  {
    id: 8,
    src: "/boda/54.webp",
    alt: "Momentos",
    size: "small",
  },
  {
    id: 9,
    src: "/boda/57.webp",
    alt: "Momentos",
    size: "small",
  },
  {
    id: 10,
    src: "/boda/58.webp",
    alt: "Momentos",
    size: "wide",
  },
  {
    id: 11,
    src: "/boda/Y&M-60.webp",
    alt: "Compromiso",
    size: "wide",
  },
  {
    id: 12,
    src: "/boda/Y&M-52.webp",
    alt: "Sesión",
    size: "small",
  },
  {
    id: 13,
    src: "/boda/Y&M-45.webp",
    alt: "Momentos",
    size: "tall",
  },
  {
    id: 14,
    src: "/boda/Y&M-29.webp",
    alt: "Sesión",
    size: "tall",
  },
  {
    id: 15,
    src: "/boda/Y&M-53.webp",
    alt: "Momentos",
    size: "small",
  },
  {
    id: 16,
    src: "/boda/Y&M-64.webp",
    alt: "Viaje",
    size: "wide",
  },
];